In [1]:
import numpy   as np
np

<module 'numpy' from 'C:\\Users\\paulo\\anaconda3\\envs\\dnc\\lib\\site-packages\\numpy\\__init__.py'>

In [3]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', '

In [6]:
array = np.array([1,2,3,4,5])

In [7]:
array[0]

1

In [8]:
array[0:]

array([1, 2, 3, 4, 5])

In [9]:
array.ndim

1

In [10]:
notas = [10,8,4,6]

In [11]:
np.array(notas)

array([10,  8,  4,  6])

In [20]:
notas_s0 = notas.copy()
notas_s1 = [5,6,5,6]
notas_semestres = [notas_s0, notas_s1]
notas_semestres

[[10, 8, 4, 6], [5, 6, 5, 6]]

In [21]:
array_2d = np.array(notas_semestres)
array_2d

array([[10,  8,  4,  6],
       [ 5,  6,  5,  6]])

In [16]:
array_2d.ndim

2

In [24]:
notas_ano0 = notas_semestres.copy()
notas_ano1 = notas_semestres.copy()
notas_ano = [notas_ano0, notas_ano1]
notas_ano

[[[10, 8, 4, 6], [5, 6, 5, 6]], [[10, 8, 4, 6], [5, 6, 5, 6]]]

In [26]:
array_3d = np.array(notas_ano)
array_3d

array([[[10,  8,  4,  6],
        [ 5,  6,  5,  6]],

       [[10,  8,  4,  6],
        [ 5,  6,  5,  6]]])

In [28]:
np.zeros([4,2,4])

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [29]:
np.ones([4,2,4])

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [30]:
np.full([4,2,4],100)

array([[[100, 100, 100, 100],
        [100, 100, 100, 100]],

       [[100, 100, 100, 100],
        [100, 100, 100, 100]],

       [[100, 100, 100, 100],
        [100, 100, 100, 100]],

       [[100, 100, 100, 100],
        [100, 100, 100, 100]]])

In [31]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
np.random.rand(4,2,4)

array([[[0.77010939, 0.50350651, 0.61706429, 0.75402919],
        [0.01399089, 0.6869248 , 0.01283365, 0.60945502]],

       [[0.58903585, 0.42165647, 0.08374938, 0.96027122],
        [0.1797809 , 0.18133779, 0.52044496, 0.6027319 ]],

       [[0.14128207, 0.35545577, 0.1788943 , 0.33995859],
        [0.9867726 , 0.08429247, 0.5557175 , 0.50750855]],

       [[0.25959757, 0.72528362, 0.72983719, 0.70701234],
        [0.83787927, 0.12901255, 0.88176677, 0.83688545]]])

In [33]:
#crinado uma lista aleatória
lista = list(range(0,10**6))

In [35]:
#tamanho da lista
len(lista)

1000000

In [ ]:
# atribuindo a lista no numpy

